{"name": "test_update_user_without_auth_password_error_message", "status": "passed", "start": 1732447987555, "stop": 1732447987736, "uuid": "7f992072-2a72-4856-b0c1-8b8703e23e29", "historyId": "08eeed589af1bf2e7822ce3dc5ef572a", "testCaseId": "08eeed589af1bf2e7822ce3dc5ef572a", "fullName": "tests.test_updata_user_data.TestUserUpdate#test_update_user_without_auth_password_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_updata_user_data"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-BEKDSUT"}, {"name": "thread", "value": "11160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_updata_user_data"}]}