{"name": "test_update_user_without_auth_email_error_message", "status": "passed", "start": 1732447986944, "stop": 1732447987298, "uuid": "65cd23e4-2a4e-4e78-85af-1429df0c22e9", "historyId": "01074df4bda90d8b34c956f0ab34303a", "testCaseId": "01074df4bda90d8b34c956f0ab34303a", "fullName": "tests.test_updata_user_data.TestUserUpdate#test_update_user_without_auth_email_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_updata_user_data"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-BEKDSUT"}, {"name": "thread", "value": "11160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_updata_user_data"}]}